In [4]:
import pandas as pd
import numpy as np

In [200]:
df = pd.read_csv('train.csv')
df.head()

employee_id         department     region   education gender  \
0         8724         Technology  region_26  Bachelor's      m   
1        74430                 HR   region_4  Bachelor's      f   
2        72255  Sales & Marketing  region_13  Bachelor's      m   
3        38562        Procurement   region_2  Bachelor's      f   
4        64486            Finance  region_29  Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   24                   NaN   
1               other                1   31                   3.0   
2               other                1   31                   1.0   
3               other                3   31                   2.0   
4            sourcing                1   30                   4.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
0                  1              1            0                  77  
1                  5              0            0                  51  
2                  4              0            0                  47  
3                  9              0            0                  65  
4                  7              0            0                  61

In [201]:
import tensorflow as tf

In [202]:
tf.__version__

'1.13.1'

In [203]:
df.isnull().sum()

employee_id                0
department                 0
region                     0
education               1034
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    1812
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
dtype: int64

In [204]:
df.groupby(['gender','is_promoted']).count()

KeyError: 'is_promoted'

In [205]:
df.groupby('gender').count()

employee_id  department  region  education  recruitment_channel  \
gender                                                                    
f              6894        6894    6894       6715                 6894   
m             16596       16596   16596      15741                16596   

        no_of_trainings    age  previous_year_rating  length_of_service  \
gender                                                                    
f                  6894   6894                  6392               6894   
m                 16596  16596                 15286              16596   

        KPIs_met >80%  awards_won?  avg_training_score  
gender                                                  
f                6894         6894                6894  
m               16596        16596               16596

In [206]:
df = df.drop(['education'],axis=1)

In [207]:
df.isnull().sum()

employee_id                0
department                 0
region                     0
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    1812
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
dtype: int64

In [208]:
df.corr()

employee_id  no_of_trainings       age  \
employee_id              1.000000        -0.005433  0.000920   
no_of_trainings         -0.005433         1.000000 -0.085509   
age                      0.000920        -0.085509  1.000000   
previous_year_rating    -0.005963        -0.047348  0.016421   
length_of_service        0.011781        -0.061095  0.644515   
KPIs_met >80%            0.006285        -0.040020 -0.027661   
awards_won?              0.000118         0.001892 -0.005457   
avg_training_score      -0.011735         0.048121 -0.035823   

                      previous_year_rating  length_of_service  KPIs_met >80%  \
employee_id                      -0.005963           0.011781       0.006285   
no_of_trainings                  -0.047348          -0.061095      -0.040020   
age                               0.016421           0.644515      -0.027661   
previous_year_rating              1.000000           0.003047       0.349350   
length_of_service                 0.003047           1.000000      -0.078121   
KPIs_met >80%                     0.349350          -0.078121       1.000000   
awards_won?                       0.027410          -0.042083       0.108288   
avg_training_score                0.064122          -0.028643       0.072981   

                      awards_won?  avg_training_score  
employee_id              0.000118           -0.011735  
no_of_trainings          0.001892            0.048121  
age                     -0.005457           -0.035823  
previous_year_rating     0.027410            0.064122  
length_of_service       -0.042083           -0.028643  
KPIs_met >80%            0.108288            0.072981  
awards_won?              1.000000            0.073857  
avg_training_score       0.073857            1.000000

In [209]:
df[df['previous_year_rating'].isnull()]

employee_id         department     region gender recruitment_channel  \
0             8724         Technology  region_26      m            sourcing   
21            5677         Technology  region_17      m            sourcing   
32           67672         Technology  region_17      m               other   
39           55325          Analytics  region_22      m               other   
47           44159          Analytics  region_22      m               other   
...            ...                ...        ...    ...                 ...   
23406        53291         Operations   region_4      m            sourcing   
23436        10138         Technology   region_2      f            referred   
23445        65765          Analytics  region_31      m            sourcing   
23479        39410  Sales & Marketing   region_2      m               other   
23488         1186        Procurement  region_31      m            sourcing   

       no_of_trainings  age  previous_year_rating  length_of_service  \
0                    1   24                   NaN                  1   
21                   1   25                   NaN                  1   
32                   1   29                   NaN                  1   
39                   1   25                   NaN                  1   
47                   1   31                   NaN                  1   
...                ...  ...                   ...                ...   
23406                1   32                   NaN                  1   
23436                1   29                   NaN                  1   
23445                3   28                   NaN                  1   
23479                3   20                   NaN                  1   
23488                3   27                   NaN                  1   

       KPIs_met >80%  awards_won?  avg_training_score  
0                  1            0                  77  
21                 0            0                  80  
32                 1            0                  85  
39                 0            0                  88  
47                 1            0                  84  
...              ...          ...                 ...  
23406              1            0                  62  
23436              0            0                  79  
23445              0            0                  86  
23479              0            0                  49  
23488              0            0                  70  

[1812 rows x 12 columns]

In [210]:
df['previous_year_rating'].unique()

array([nan,  3.,  1.,  2.,  4.,  5.])

In [211]:
df.corr()

employee_id  no_of_trainings       age  \
employee_id              1.000000        -0.005433  0.000920   
no_of_trainings         -0.005433         1.000000 -0.085509   
age                      0.000920        -0.085509  1.000000   
previous_year_rating    -0.005963        -0.047348  0.016421   
length_of_service        0.011781        -0.061095  0.644515   
KPIs_met >80%            0.006285        -0.040020 -0.027661   
awards_won?              0.000118         0.001892 -0.005457   
avg_training_score      -0.011735         0.048121 -0.035823   

                      previous_year_rating  length_of_service  KPIs_met >80%  \
employee_id                      -0.005963           0.011781       0.006285   
no_of_trainings                  -0.047348          -0.061095      -0.040020   
age                               0.016421           0.644515      -0.027661   
previous_year_rating              1.000000           0.003047       0.349350   
length_of_service                 0.003047           1.000000      -0.078121   
KPIs_met >80%                     0.349350          -0.078121       1.000000   
awards_won?                       0.027410          -0.042083       0.108288   
avg_training_score                0.064122          -0.028643       0.072981   

                      awards_won?  avg_training_score  
employee_id              0.000118           -0.011735  
no_of_trainings          0.001892            0.048121  
age                     -0.005457           -0.035823  
previous_year_rating     0.027410            0.064122  
length_of_service       -0.042083           -0.028643  
KPIs_met >80%            0.108288            0.072981  
awards_won?              1.000000            0.073857  
avg_training_score       0.073857            1.000000

In [212]:
df.columns

Index(['employee_id', 'department', 'region', 'gender', 'recruitment_channel',
       'no_of_trainings', 'age', 'previous_year_rating', 'length_of_service',
       'KPIs_met >80%', 'awards_won?', 'avg_training_score'],
      dtype='object')

In [213]:
xtemp = df[['age','length_of_service','KPIs_met >80%','previous_year_rating']]

In [214]:
xtemp.head()

age  length_of_service  KPIs_met >80%  previous_year_rating
0   24                  1              1                   NaN
1   31                  5              0                   3.0
2   31                  4              0                   1.0
3   31                  9              0                   2.0
4   30                  7              0                   4.0

In [215]:
xtemp = xtemp.dropna()

In [216]:
xtemp.isnull().sum()

age                     0
length_of_service       0
KPIs_met >80%           0
previous_year_rating    0
dtype: int64

In [217]:
x_l = xtemp.iloc[:,0:3].values
y_l = xtemp.iloc[:,-1].values

In [218]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_l, y_l)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [219]:
xpred = df[['age','length_of_service','KPIs_met >80%','previous_year_rating']]

In [220]:
xpred = xpred[xpred['previous_year_rating'].isnull()]

In [221]:
xpred.head()

age  length_of_service  KPIs_met >80%  previous_year_rating
0    24                  1              1                   NaN
21   25                  1              0                   NaN
32   29                  1              1                   NaN
39   25                  1              0                   NaN
47   31                  1              1                   NaN

In [222]:
x_p = xpred.iloc[:,0:3].values
x_p

array([[24,  1,  1],
       [25,  1,  0],
       [29,  1,  1],
       ...,
       [28,  1,  0],
       [20,  1,  0],
       [27,  1,  0]], dtype=int64)

In [223]:
res = regressor.predict(x_p)
res

array([3.86869742, 2.94369387, 3.87865092, ..., 2.94966597, 2.93374037,
       2.94767527])

In [224]:
import numpy as np
np.floor(res)

array([3., 2., 3., ..., 2., 2., 2.])

In [225]:
nullindexlist=df[df['previous_year_rating'].isnull()].index.tolist()

In [226]:
nullindexlist

[0,
 21,
 32,
 39,
 47,
 53,
 54,
 63,
 102,
 103,
 127,
 154,
 161,
 162,
 164,
 172,
 174,
 187,
 191,
 204,
 206,
 216,
 222,
 223,
 233,
 244,
 249,
 271,
 286,
 296,
 327,
 341,
 343,
 368,
 382,
 409,
 415,
 416,
 426,
 428,
 436,
 443,
 449,
 467,
 469,
 471,
 505,
 535,
 540,
 549,
 572,
 579,
 616,
 625,
 636,
 647,
 651,
 660,
 664,
 671,
 673,
 707,
 713,
 720,
 731,
 733,
 777,
 783,
 784,
 789,
 806,
 809,
 821,
 854,
 860,
 886,
 915,
 925,
 934,
 951,
 961,
 966,
 982,
 1000,
 1021,
 1024,
 1025,
 1043,
 1046,
 1064,
 1071,
 1080,
 1085,
 1096,
 1172,
 1185,
 1187,
 1220,
 1243,
 1251,
 1259,
 1267,
 1275,
 1293,
 1294,
 1305,
 1327,
 1328,
 1338,
 1340,
 1361,
 1376,
 1386,
 1401,
 1406,
 1410,
 1412,
 1422,
 1430,
 1457,
 1469,
 1503,
 1504,
 1514,
 1526,
 1530,
 1531,
 1555,
 1558,
 1576,
 1579,
 1593,
 1597,
 1609,
 1615,
 1627,
 1640,
 1649,
 1673,
 1683,
 1702,
 1738,
 1745,
 1752,
 1797,
 1840,
 1861,
 1873,
 1909,
 1911,
 1938,
 1953,
 1967,
 1976,
 1977,
 1982,


In [228]:
count=0
temp = df['previous_year_rating']
z = int(temp.shape[0])
z
import numpy as np
for i in range(0,z-1):
    if np.isnan(temp[i]):
        temp[i] = np.floor(res[count])
        count =count+1




C:\Users\PAVAN\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [229]:
temp.head(11)

0     3.0
1     3.0
2     1.0
3     2.0
4     4.0
5     3.0
6     5.0
7     3.0
8     4.0
9     5.0
10    5.0
Name: previous_year_rating, dtype: float64

In [230]:
temp.isnull().sum()

0

In [231]:
df = pd.concat([df.drop(['previous_year_rating'],axis=1),temp], axis=1)

In [232]:
df.isnull().sum()

employee_id             0
department              0
region                  0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
previous_year_rating    0
dtype: int64

In [233]:
df.head()

employee_id         department     region gender recruitment_channel  \
0         8724         Technology  region_26      m            sourcing   
1        74430                 HR   region_4      f               other   
2        72255  Sales & Marketing  region_13      m               other   
3        38562        Procurement   region_2      f               other   
4        64486            Finance  region_29      m            sourcing   

   no_of_trainings  age  length_of_service  KPIs_met >80%  awards_won?  \
0                1   24                  1              1            0   
1                1   31                  5              0            0   
2                1   31                  4              0            0   
3                3   31                  9              0            0   
4                1   30                  7              0            0   

   avg_training_score  previous_year_rating  
0                  77                   3.0  
1                  51                   3.0  
2                  47                   1.0  
3                  65                   2.0  
4                  61                   4.0

In [234]:
df = df.dropna()

In [235]:
df.isnull().sum()

employee_id             0
department              0
region                  0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
previous_year_rating    0
dtype: int64

In [236]:
df.head()

employee_id         department     region gender recruitment_channel  \
0         8724         Technology  region_26      m            sourcing   
1        74430                 HR   region_4      f               other   
2        72255  Sales & Marketing  region_13      m               other   
3        38562        Procurement   region_2      f               other   
4        64486            Finance  region_29      m            sourcing   

   no_of_trainings  age  length_of_service  KPIs_met >80%  awards_won?  \
0                1   24                  1              1            0   
1                1   31                  5              0            0   
2                1   31                  4              0            0   
3                3   31                  9              0            0   
4                1   30                  7              0            0   

   avg_training_score  previous_year_rating  
0                  77                   3.0  
1                  51                   3.0  
2                  47                   1.0  
3                  65                   2.0  
4                  61                   4.0

In [237]:
df.count()

employee_id             23490
department              23490
region                  23490
gender                  23490
recruitment_channel     23490
no_of_trainings         23490
age                     23490
length_of_service       23490
KPIs_met >80%           23490
awards_won?             23490
avg_training_score      23490
previous_year_rating    23490
dtype: int64

In [238]:
df.columns

Index(['employee_id', 'department', 'region', 'gender', 'recruitment_channel',
       'no_of_trainings', 'age', 'length_of_service', 'KPIs_met >80%',
       'awards_won?', 'avg_training_score', 'previous_year_rating'],
      dtype='object')

In [239]:
dataframe = df[['department', 'region', 'recruitment_channel',
       'no_of_trainings', 'age', 'length_of_service', 'KPIs_met >80%',
       'awards_won?', 'avg_training_score','is_promoted']]

In [240]:
dataframe.head()

department     region recruitment_channel  no_of_trainings  age  \
0         Technology  region_26            sourcing                1   24   
1                 HR   region_4               other                1   31   
2  Sales & Marketing  region_13               other                1   31   
3        Procurement   region_2               other                3   31   
4            Finance  region_29            sourcing                1   30   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
0                  1              1            0                  77  
1                  5              0            0                  51  
2                  4              0            0                  47  
3                  9              0            0                  65  
4                  7              0            0                  61

In [241]:
dataframe['department'].unique()

array(['Technology', 'HR', 'Sales & Marketing', 'Procurement', 'Finance',
       'Analytics', 'Operations', 'Legal', 'R&D'], dtype=object)

In [242]:
dataframe.groupby(['department','is_promoted']).count()

KeyError: 'is_promoted'

In [243]:
appendvr2testdf = pd.get_dummies(dataframe[['department']],drop_first=True)
dataframe = pd.concat([dataframe.drop(['department'],axis=1),appendvr2testdf], axis=1)

In [244]:
appendvr2testdf = pd.get_dummies(dataframe[['recruitment_channel']],drop_first=True)
dataframe = pd.concat([dataframe.drop(['recruitment_channel'],axis=1),appendvr2testdf], axis=1)

In [245]:
dataframe.head()

region  no_of_trainings  age  length_of_service  KPIs_met >80%  \
0  region_26                1   24                  1              1   
1   region_4                1   31                  5              0   
2  region_13                1   31                  4              0   
3   region_2                3   31                  9              0   
4  region_29                1   30                  7              0   

   awards_won?  avg_training_score  department_Finance  department_HR  \
0            0                  77                   0              0   
1            0                  51                   0              1   
2            0                  47                   0              0   
3            0                  65                   0              0   
4            0                  61                   1              0   

   department_Legal  department_Operations  department_Procurement  \
0                 0                      0                       0   
1                 0                      0                       0   
2                 0                      0                       0   
3                 0                      0                       1   
4                 0                      0                       0   

   department_R&D  department_Sales & Marketing  department_Technology  \
0               0                             0                      1   
1               0                             0                      0   
2               0                             1                      0   
3               0                             0                      0   
4               0                             0                      0   

   recruitment_channel_referred  recruitment_channel_sourcing  
0                             0                             1  
1                             0                             0  
2                             0                             0  
3                             0                             0  
4                             0                             1

In [246]:
dataframe['region'].unique()

array(['region_26', 'region_4', 'region_13', 'region_2', 'region_29',
       'region_7', 'region_22', 'region_16', 'region_17', 'region_24',
       'region_11', 'region_27', 'region_9', 'region_20', 'region_34',
       'region_23', 'region_8', 'region_14', 'region_31', 'region_19',
       'region_5', 'region_28', 'region_15', 'region_3', 'region_25',
       'region_12', 'region_21', 'region_30', 'region_10', 'region_33',
       'region_32', 'region_6', 'region_1', 'region_18'], dtype=object)

In [247]:
dataframe.columns

Index(['region', 'no_of_trainings', 'age', 'length_of_service',
       'KPIs_met >80%', 'awards_won?', 'avg_training_score',
       'department_Finance', 'department_HR', 'department_Legal',
       'department_Operations', 'department_Procurement', 'department_R&D',
       'department_Sales & Marketing', 'department_Technology',
       'recruitment_channel_referred', 'recruitment_channel_sourcing'],
      dtype='object')

In [248]:
dataframe = dataframe[['no_of_trainings', 'age', 'length_of_service',
       'KPIs_met >80%', 'awards_won?', 'avg_training_score',
       'department_Finance', 'department_HR', 'department_Legal',
       'department_Operations', 'department_Procurement', 'department_R&D',
       'department_Sales & Marketing', 'department_Technology',
       'recruitment_channel_referred', 'recruitment_channel_sourcing','is_promoted']]

In [249]:
dataframe.head()

no_of_trainings  age  length_of_service  KPIs_met >80%  awards_won?  \
0                1   24                  1              1            0   
1                1   31                  5              0            0   
2                1   31                  4              0            0   
3                3   31                  9              0            0   
4                1   30                  7              0            0   

   avg_training_score  department_Finance  department_HR  department_Legal  \
0                  77                   0              0                 0   
1                  51                   0              1                 0   
2                  47                   0              0                 0   
3                  65                   0              0                 0   
4                  61                   1              0                 0   

   department_Operations  department_Procurement  department_R&D  \
0                      0                       0               0   
1                      0                       0               0   
2                      0                       0               0   
3                      0                       1               0   
4                      0                       0               0   

   department_Sales & Marketing  department_Technology  \
0                             0                      1   
1                             0                      0   
2                             1                      0   
3                             0                      0   
4                             0                      0   

   recruitment_channel_referred  recruitment_channel_sourcing  
0                             0                             1  
1                             0                             0  
2                             0                             0  
3                             0                             0  
4                             0                             1

In [253]:
X= dataframe.iloc[:, :]
y = dataframe.iloc[:,-1]

In [251]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size = 0.25,random_state=0)


ValueError: Found input variables with inconsistent numbers of samples: [23490, 54808]

In [193]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

# Prediction the test set result
y_pred = classifier.predict(X_train)

C:\Users\PAVAN\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [194]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train, y_pred)

In [195]:
cm


array([[37497,    95],
       [ 2857,   657]], dtype=int64)

In [254]:
ans = classifier.predict(X)

In [197]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test,ans)

In [198]:
cm1

array([[12520,    28],
       [  935,   219]], dtype=int64)

In [199]:
(12520+219)/(12520+28+935+219)

0.929718289300832

In [255]:
ans

array([0., 0., 0., ..., 0., 0., 1.])

In [258]:
np.save(ans.npy)